### ISSUE TITLE
Apps using translator crash on exit

### ISSUE THREAD

**Issue by humdingerb** [threedeyes/PDFTranslator#1]
After installing PDFTranslator, any app that uses data translators crashes on exit.
Since I cannot attach files at github with Web+, stacktraces:
https://linx.li/aboutsystem-182752-debug-23-11-2019-09-23-45.report
https://linx.li/stylededit-182545-debug-23-11-2019-09-20-59.report
https://linx.li/stylededit-182545-debug-23-11-2019-09-20-59.report

**Comment by threedeyes** [comment]
It's not a PDFTranslator problem. We need bump revision for mupdf package for rebuild after jp2 library update. PDFTranslator works fine after mupdf rebuild.
